kind: pipeline
name: default

steps:
- name: build
  image: gradle:6.6.1-jdk11
  commands:
  - gradle build

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    username: Drone CI
    message: >
      {{#success build.status}}
        Build {{build.number}} ({{build.commit}}) succeeded!
      {{else}}
        Build {{build.number}} ({{build.commit}}) failed.
      {{/success}}
  
- name: publish to github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: build/libs/*
  when:
    event: tag
